CREATE TABLE event(
    uuid VARCHAR(128) UNIQUE NOT NULL PRIMARY KEY,
    type VARCHAR(64),
    file_uuid VARCHAR(128)
);

CREATE TABLE file(
    uuid VARCHAR(128) UNIQUE NOT NULL PRIMARY KEY,
    filename VARCHAR(4096)
);
